import { StartupProvider } from "./StartupContext";
import "./globals.css";
import Bootstrap from "./services/Bootstrap";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Bootstrap />
      <body>
        <StartupProvider>
          <div className="container-fluid p-0 vh-100 overflow-hidden">
            {children}
          </div>
        </StartupProvider>
      </body>
    </html>
  );
}
